ALTER TABLE residents ADD COLUMN email TEXT NOT NULL DEFAULT '';
ALTER TABLE residents ADD COLUMN tenant_email TEXT NOT NULL DEFAULT '';
ALTER TABLE residents ADD COLUMN tenant_phone TEXT NOT NULL DEFAULT '';
